version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"