version: "2"
linters:
  enable:
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - misspell
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines