# Copyright (C) 2024-2026 Bryce Thuilot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

header:
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: Bryce Thuilot
    copyright-year: '2024-2026'
    content: |
      Copyright (C) [year] [owner]

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the FSF, either version 3 of the License, or (at your option) any later version.
      See the LICENSE file in the root of this repository for full license text or
      visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

  paths:
    - '**/*.go'
    - 'Makefile'
    - '**/*.sh'
    - '**/*.yaml'
    - '**/Dockerfile'

  comment: on-failure