# Copyright (C) 2024-2026 Bryce Thuilot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

on:
  release:
    types: [created]

permissions:
  contents: read

env:
  GO_VERSION: 1.25
  VERSION: ${{ github.event.release.name }}

jobs:
  publish-ci-script:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Publish script
        run: |
          mkdir -p pages/
          cp ./scripts/ci-scan.sh pages/ci-scan
      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v3
        with:
          path: 'pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
  binary-releases-matrix:
    name: release binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ env.GO_VERSION }}
      #- name: install cosign
      #  uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3
      - name: build
        run: |
          make build
      - name: upload release
        run: |
          sha256sum ./bin/git-lost-and-found > "$BIN_SHA"
          cp ./bin/git-lost-and-found "$BIN_NAME"
          gh release upload ${{ github.ref_name }} "$BIN_NAME" "$BIN_SHA"
        env:
          GH_TOKEN: ${{ github.token }}
          BIN_NAME: "git-lost-and-found-${{ matrix.goos }}-${{ matrix.goarch }}"
          BIN_SHA: "git-lost-and-found-${{ matrix.goos }}-${{ matrix.goarch }}.sha256"
  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    env:
      TAG: "ghcr.io/${{ github.repository_owner }}/git-lost-and-found:${{ github.ref_name }}"
      LATEST: "ghcr.io/${{ github.repository_owner }}/git-lost-and-found:latest"
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup qemu
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - name: setup buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: install cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v3
      - name: docker build
        id: docker-build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.TAG }},${{ env.LATEST }}
      - name: sign image
        env:
          DIGEST: ${{ steps.docker-build.outputs.digest }}
        run: cosign sign --yes ${TAG}@${DIGEST} ${LATEST}@${DIGEST}